### ISSUE TITLE
no output wav files

### ISSUE THREAD

**Issue by ggsonic** [Saurabh-29/waveglow_cuda_inference#3]
Ubuntu 18.04, titan xp. cuda10.1
`./waveglow_tts filename.txt outputdir` can not output any wav file

**Comment by Saurabh-29** [comment]
Can you share the exact output/error full-trace?

**Comment by ggsonic** [comment]
sorry  my fault. I commented out DEBUG things. and  log_d is void(). audio.log not been called. everything ok now.
